# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR to Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        RELEASE_TAG="${GITHUB_REF/refs\/tags\//}"
        echo "Creating a release for tag $RELEASE_TAG"
        # Create a GitHub release using the jar file
        gh release create "$RELEASE_TAG" target/my-spark-test-1.0.jar
      env:
        GITHUB_TOKEN: ${{ github.token }}
